Repository jpquast/protti, pull requests merged in 2020-09, with the labels that each got.

#56 Treatment enrichment
  NAMESPACE
  R/treatment_enrichment.R
  man/treatment_enrichment.Rd
Labels: new feature

#62 Update fetch_uniprot default columns
  R/fetch_uniprot.R
  man/fetch_uniprot.Rd
Labels: enhancement

#63 Update fetch_kegg, add uniprot id
  R/fetch_kegg.R
Labels: enhancement

#59 Woods plot
  NAMESPACE
  R/woods_plot.R
  man/woods_plot.Rd
Labels: new feature

#65 Add license
  .Rbuildignore
  DESCRIPTION
  LICENSE
  LICENSE.md
Labels: documentation

#64 Add calculate_protein_abundance function
  DESCRIPTION
  NAMESPACE
  R/calculate_protein_abundance.R
  man/calculate_protein_abundance.Rd
Labels: new feature

#61 Add fetch_mobidb function
  DESCRIPTION
  NAMESPACE
  R/fetch_mobidb.R
  man/fetch_mobidb.Rd
Labels: new feature

#60 Add barcode_plot function
  NAMESPACE
  R/barcode_plot.R
  man/barcode_plot.Rd
Labels: new feature

#66 Add kegg_enrichment function
  NAMESPACE
  R/kegg_enrichment.R
  man/kegg_enrichment.Rd
Labels: new feature

#67 Go analysis
  DESCRIPTION
  NAMESPACE
  R/fetch_go.R
  R/go_enrichment.R
  man/fetch_go.Rd
  man/go_enrichment.Rd
Labels: new feature

#68 Add qc_contaminants function
  DESCRIPTION
  NAMESPACE
  R/qc_contaminants.R
  man/qc_contaminants.Rd
Labels: new feature

#69 Impute fix
  NAMESPACE
  R/diff_abundance.R
  R/impute.R
  R/volcano_protti.R
  README.md
  man/impute.Rd
Labels: bug

#70 Add biocViews: to DESCRIPTION file
  DESCRIPTION
Labels: enhancement

#71 Color adjustments
  R/barcode_plot.R
  R/qc_charge_states.R
  R/qc_contaminants.R
  R/qc_ids.R
  R/qc_log2_intensity_distribution.R
  R/qc_missed_cleavages.R
  R/qc_pca.R
  R/qc_peptide_type.R
  R/qc_proteome_coverage.R
  R/qc_run_intensity.R
  R/qc_sequence_coverage.R
  R/volcano_protti.R
Labels: enhancement

#72 Add function qc_data_completeness
  NAMESPACE
  R/qc_data_completeness.R
  man/qc_data_completeness.Rd
Labels: new feature

#73 qc_ids color update
  R/qc_ids.R
Labels: enhancement

#77 Fit drc 4p parallelisation
  DESCRIPTION
  NAMESPACE
  R/fit_drc_4p.R
  R/parallel_fit_drc_4p.R
  R/plot_drc_4p.R
  R/qc_sample_correlation.R
  man/fit_drc_4p.Rd
  man/parallel_fit_drc_4p.Rd
  man/plot_drc_4p.Rd
Labels: enhancement, new feature

#75 Bugfix
  R/qc_peptide_type.R
  man/barcode_plot.Rd
  man/qc_contaminants.Rd
Labels: issue
