Repository jpquast/protti, pull requests merged in 2020-08, with the labels that each got.

#47 Update try query
  R/fetch_pdb.R
  R/try_query.R
  man/try_query.Rd
Labels: bug

#48 qc_peptide_type add methods
  R/qc_peptide_type.R
  man/qc_peptide_type.Rd
Labels: enhancement

#49 Add qc_proteome_coverage function
  NAMESPACE
  R/qc_proteome_coverage.R
  man/qc_proteome_coverage.Rd
Labels: new feature

#50 Add qc_peak_width function
  NAMESPACE
  R/qc_peak_width.R
  man/qc_peak_width.Rd
Labels: new feature

#51 Add ttest_protti function
  NAMESPACE
  R/ttest_protti.R
  man/ttest_protti.Rd
Labels: new feature

#52 Speed up assign_missingness
  NAMESPACE
  R/assign_missingness.R
  man/assign_missingness.Rd
Labels: documentation, enhancement

#53 Diff abundance
  DESCRIPTION
  NAMESPACE
  R/diff_abundance.R
  R/impute.R
  R/ttest_protti.R
  man/diff_abundance.Rd
  man/impute.Rd
Labels: new feature

#57 Add fetch_kegg and update try_query
  NAMESPACE
  R/fetch_kegg.R
  R/try_query.R
  man/fetch_kegg.Rd
  man/try_query.Rd
Labels: new feature
