Repository jpquast/protti, pull requests merged in 2021-02, with the labels that each got.

#99 Add QC vignette and tiny change in plot_drc_4p
  .Rbuildignore
  .gitignore
  DESCRIPTION
  R/qc_charge_states.R
  R/qc_cvs.R
  R/qc_data_completeness.R
  R/qc_ids.R
  R/qc_log2_intensity_distribution.R
  R/qc_median_intensities.R
  R/qc_missed_cleavages.R
  R/qc_pca.R
  R/qc_peak_width.R
  R/qc_peptide_type.R
  R/qc_run_intensity.R
  R/qc_sample_correlation.R
  R/qc_sequence_coverage.R
  man/qc_median_intensities.Rd
  man/qc_peak_width.Rd
  man/qc_sample_correlation.Rd
  man/qc_sequence_coverage.Rd
  tests/testthat/test-qc_functions.R
  vignettes/.gitignore
  vignettes/quality_control_workflow.Rmd
Labels: documentation

#102 GitHub actions test
  .Rbuildignore
  .github/.gitignore
  .github/workflows/R-CMD-check.yaml
  .github/workflows/test-coverage.yaml
  .travis.yml
  DESCRIPTION
  README.Rmd
  README.md
  codecov.yml
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
Labels: enhancement

#103 Update README codecovr
  .github/workflows/R-CMD-check.yaml
  README.md
Labels: bug

#104 Create qc_intensity_distribution
  NAMESPACE
  R/qc_intensity_distribution.R
  R/qc_log2_intensity_distribution.R
  R/qc_run_intensity.R
  man/qc_intensity_distribution.Rd
  man/qc_log2_intensity_distribution.Rd
  man/qc_run_intensity.Rd
  tests/testthat/test-qc_functions.R
  vignettes/quality_control_workflow.Rmd
Labels: enhancement

#105 Add pkgdown website
  .Rbuildignore
  .github/workflows/pkgdown.yaml
  .gitignore
  R/go_enrichment.R
  R/impute.R
  R/qc_contaminants.R
  _pkgdown.yml
  man/go_enrichment.Rd
  man/impute.Rd
  man/qc_contaminants.Rd
Labels: new feature

#107 Update and typo fixes in QC vignette
  vignettes/quality_control_workflow.Rmd
Labels: documentation

#106 Move limma to suggests
  DESCRIPTION
  NAMESPACE
  R/calculate_protein_abundance.R
  R/diff_abundance.R
  R/drc_4p.R
  R/extract_metal_binders.R
  R/fetch_chebi.R
  R/fetch_mobidb.R
  R/find_all_subs.R
  R/find_chebis.R
  R/fit_drc_4p.R
  R/parallel_fit_drc_4p.R
  R/protein_abundance_normalisation.R
  R/qc_sample_correlation.R
Labels: enhancement

#109 Update README
  README.Rmd
  README.md
  man/figures/README-volcano-1.png
Labels: documentation

#110 Add more protti colours
  R/data.R
  R/plot_peptide_profiles.R
  R/qc_charge_states.R
  R/qc_contaminants.R
  R/qc_cvs.R
  R/qc_ids.R
  R/qc_missed_cleavages.R
  R/qc_pca.R
  R/qc_peak_width.R
  R/qc_peptide_type.R
  data-raw/protti_colors.R
  data-raw/protti_colours.R
  data/protti_colors.rda
  data/protti_colours.rda
  man/protti_colors.Rd
  man/protti_colours.Rd
Labels: enhancement

#111 Fix bugs and improvements
  R/calculate_protein_abundance.R
  R/fetch_uniprot.R
  R/plot_peptide_profiles.R
  R/qc_intensity_distribution.R
  R/qc_pca.R
  R/qc_peak_width.R
  R/volcano_protti.R
  README.Rmd
  README.md
  man/figures/README-volcano-1.png
  man/plot_peptide_profiles.Rd
  man/qc_intensity_distribution.Rd
  man/volcano_protti.Rd
  tests/testthat/test-qc_functions.R
  tests/testthat/test-workflow.R
  vignettes/quality_control_workflow.Rmd
Labels: bug, enhancement

#112 Support facets in volcano
  R/volcano_protti.R
  man/volcano_protti.Rd
Labels: enhancement

#113 Stringdb move and bug fixes
  DESCRIPTION
  NAMESPACE
  R/fetch_uniprot.R
  R/go_enrichment.R
  R/kegg_enrichment.R
  R/network_analysis.R
  R/plot_drc_4p.R
  R/qc_intensity_distribution.R
  R/qc_proteome_coverage.R
  R/volcano_protti.R
  R/woods_plot.R
  man/fetch_uniprot.Rd
  man/kegg_enrichment.Rd
  man/plot_drc_4p.Rd
  man/qc_intensity_distribution.Rd
  man/qc_proteome_coverage.Rd
  man/volcano_protti.Rd
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
  tests/testthat/test-qc_functions.R
  tests/testthat/test-workflow.R
Labels: bug, documentation, enhancement
