Repository jpquast/protti, pull requests merged in 2021-01, with the labels that each got.

#93 Create synthetic data
  DESCRIPTION
  NAMESPACE
  R/assign_missingness.R
  R/barcode_plot.R
  R/calculate_protein_abundance.R
  R/create_queue.R
  R/create_synthetic_data.R
  R/diff_abundance.R
  R/fetch_kegg.R
  R/fetch_mobidb.R
  R/fetch_uniprot.R
  R/go_enrichment.R
  R/impute.R
  R/kegg_enrichment.R
  R/qc_charge_states.R
  R/qc_contaminants.R
  R/qc_cvs.R
  R/qc_ids.R
  R/qc_missed_cleavages.R
  R/qc_peak_width.R
  R/qc_peptide_type.R
  R/qc_sequence_coverage.R
  R/scale_protti.R
  R/volcano_protti.R
  R/zzz.R
  man/assign_missingness.Rd
  man/barcode_plot.Rd
  man/calculate_protein_abundance.Rd
  man/create_queue.Rd
  man/create_synthetic_data.Rd
  man/diff_abundance.Rd
  man/fetch_kegg.Rd
  man/fetch_uniprot.Rd
  man/go_enrichment.Rd
  man/impute.Rd
  man/kegg_enrichment.Rd
  man/plot_drc_4p.Rd
  man/qc_ids.Rd
  man/qc_sequence_coverage.Rd
  man/scale_protti.Rd
  tests/testthat/test-auxiliary_functions.R
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
  tests/testthat/test-fetch_functions.R
  tests/testthat/test-qc_functions.R
  tests/testthat/test-queue_functions.R
  tests/testthat/test-workflow.R
  tests/testthat/test_import.csv
Labels: bug, documentation, enhancement, new feature

#94 Add plot_peptide_profiles function
  NAMESPACE
  R/plot_peptide_profiles.R
  man/plot_peptide_profiles.Rd
  tests/testthat/test-workflow.R
Labels: new feature

#95 Adding travis-ci for automated testing
  .Rbuildignore
  .travis.yml
  README.Rmd
  README.md
Labels: enhancement

#96 add filter_cv function
  NAMESPACE
  R/filter_cv.R
  man/filter_cv.Rd
  man/plot_drc_4p.Rd
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
  tests/testthat/test-workflow.R
Labels: new feature

#97 Update travis
  .travis.yml
Labels: issue

#98 Add network_analysis function and tests
  DESCRIPTION
  NAMESPACE
  R/network_analysis.R
  man/network_analysis.Rd
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
Labels: new feature

#101 Function improvements and bug fixes
  DESCRIPTION
  NAMESPACE
  R/assign_missingness.R
  R/barcode_plot.R
  R/calculate_protein_abundance.R
  R/diff_abundance.R
  R/drc_4p.R
  R/fetch_chebi.R
  R/fetch_pdb.R
  R/fit_drc_4p.R
  R/impute.R
  R/median_normalisation.R
  R/plot_drc_4p.R
  R/qc_charge_states.R
  R/qc_contaminants.R
  R/qc_cvs.R
  R/qc_data_completeness.R
  R/qc_log2_intensity_distribution.R
  R/qc_median_intensities.R
  R/qc_peak_width.R
  R/qc_peptide_type.R
  R/qc_proteome_coverage.R
  R/qc_run_intensity.R
  R/qc_sequence_coverage.R
  R/split_metal_name.R
  R/ttest_protti.R
  R/zzz.R
  man/assign_missingness.Rd
  man/calculate_protein_abundance.Rd
  man/diff_abundance.Rd
  man/drc_4p.Rd
  man/fetch_pdb.Rd
  man/filter_cv.Rd
  man/fit_drc_4p.Rd
  man/impute.Rd
  man/plot_drc_4p.Rd
  man/qc_peptide_type.Rd
  man/ttest_protti.Rd
  tests/testthat/test-workflow.R
Labels: bug, enhancement
