Repository jpquast/protti, pull requests merged in 2021-06, with the labels that each got.

#147 Add all option to assign_missingness
  NAMESPACE
  R/assign_missingness.R
  R/diff_abundance.R
  R/fetch_chebi.R
  R/fetch_go.R
  R/fetch_mobidb.R
  R/plot_peptide_profiles.R
  R/randomise_queue.R
  R/try_query.R
  README.Rmd
  README.md
  man/assign_missingness.Rd
  man/diff_abundance.Rd
  man/fetch_mobidb.Rd
  man/randomise_queue.Rd
  man/try_query.Rd
  tests/testthat/test-workflow.R
  vignettes/data_analysis_single_dose_treatment_workflow.Rmd
Labels: enhancement

#148 Add fetch_pdb and bug fixes
  NAMESPACE
  R/diff_abundance.R
  R/extract_metal_binders.R
  R/fetch_kegg.R
  R/fetch_pdb.R
  R/fetch_uniprot.R
  R/split_metal_name.R
  R/try_query.R
  man/fetch_go.Rd
  man/fetch_pdb.Rd
  man/fetch_uniprot.Rd
  man/plot_peptide_profiles.Rd
  man/try_query.Rd
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
Labels: bug, new feature

#149 Add fetch_pdb_structure
  NAMESPACE
  R/fetch_pdb.R
  R/fetch_pdb_structure.R
  man/fetch_pdb.Rd
  man/fetch_pdb_structure.Rd
  man/try_query.Rd
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
Labels: new feature

#151 Add fetch_metal_pdb
  NAMESPACE
  R/assign_missingness.R
  R/diff_abundance.R
  R/fetch_metal_pdb.R
  R/fetch_pdb.R
  R/fetch_pdb_structure.R
  R/find_peptide_in_pdb.R
  man/fetch_metal_pdb.Rd
  man/fetch_pdb_structure.Rd
  man/find_peptide_in_pdb.Rd
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
Labels: new feature

#150 Woods plot improvements
  R/assign_missingness.R
  R/diff_abundance.R
  R/fetch_pdb.R
  R/find_peptide_in_pdb.R
  R/woods_plot.R
  man/woods_plot.Rd
  tests/testthat/test-auxiliary_functions.R
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
  vignettes/data_analysis_single_dose_treatment_workflow.Rmd
Labels: enhancement
