Repository jpquast/protti, pull requests merged in 2021-04, with the labels that each got.

#140 Remove set.seed from impute functions
  R/calculate_imputation.R
  R/fetch_mobidb.R
  R/impute.R
  R/plot_drc_4p.R
  R/randomise_queue.R
  README.Rmd
  README.md
  cran-comments.md
  man/calculate_imputation.Rd
  man/fetch_mobidb.Rd
  man/figures/README-volcano-1.png
  man/randomise_queue.Rd
  tests/testthat/test-workflow.R
  vignettes/data_analysis_dose_response_workflow.Rmd
  vignettes/data_analysis_single_dose_treatment_workflow.Rmd
  vignettes/input_preparation_workflow.Rmd
  vignettes/quality_control_workflow.Rmd
Labels: bug, enhancement

#141 Improve fetch_chebi
  R/fetch_chebi.R
Labels: enhancement

#142 Extend timeout for fetch_mobidb
  R/fetch_mobidb.R
Labels: enhancement

#143 Update README
  .Rbuildignore
  README.Rmd
  README.md
Labels: documentation

#144 implement Natalie's suggestions
  README.Rmd
  README.md
  man/figures/README-volcano-1.png
  vignettes/input_preparation_workflow.Rmd
  vignettes/quality_control_workflow.Rmd
Labels: documentation
