Repository jpquast/protti, pull requests merged in 2021-03, with the labels that each got.

#114 fix plot starting position
  R/barcode_plot.R
  man/figures/protti_logo.png
Labels: enhancement, issue

#116 Add example data
  R/data.R
  data-raw/rapamycin_10uM.R
  data-raw/rapamycin_dose_response.R
  data/rapamycin_10uM.rda
  data/rapamycin_dose_response.rda
  man/rapamycin_10uM.Rd
  man/rapamycin_dose_response.Rd
Labels: new feature

#115 Fit drc 4p improvements
  NAMESPACE
  R/assign_missingness.R
  R/diff_abundance.R
  R/fit_drc_4p.R
  R/parallel_fit_drc_4p.R
  R/plot_drc_4p.R
  R/scale_protti.R
  man/assign_missingness.Rd
  man/fit_drc_4p.Rd
  man/parallel_fit_drc_4p.Rd
  man/plot_drc_4p.Rd
  tests/testthat/test-workflow.R
Labels: enhancement, new feature

#118 Bug fixes and improvements
  R/data.R
  R/fetch_uniprot.R
  R/fit_drc_4p.R
  R/parallel_fit_drc_4p.R
  R/qc_sample_correlation.R
  R/treatment_enrichment.R
  data-raw/rapamycin_dose_response.R
  data/rapamycin_dose_response.rda
  man/fetch_uniprot.Rd
  man/fit_drc_4p.Rd
  man/parallel_fit_drc_4p.Rd
  man/rapamycin_dose_response.Rd
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
Labels: bug, enhancement

#120 Dose response workflow
  vignettes/data_analysis_dose_response_workflow.Rmd
Labels: documentation

#117 add single dose treatment vignette
  R/filter_cv.R
  R/go_enrichment.R
  R/kegg_enrichment.R
  R/treatment_enrichment.R
  R/woods_plot.R
  man/filter_cv.Rd
  man/woods_plot.Rd
  vignettes/data_analysis_single_dose_treatment_workflow.Rmd
  vignettes/quality_control_workflow.Rmd
Labels: documentation

#121 edit QC vignette + remove protein abundance normalisation function
  NAMESPACE
  R/protein_abundance_normalisation.R
  man/protein_abundance_normalisation.Rd
  tests/testthat/test-workflow.R
  vignettes/quality_control_workflow.Rmd
Labels: documentation

#122 add vignette links to readme
  README.Rmd
  README.md
  man/figures/README-volcano-1.png
Labels: documentation

#125 Input preparation vignette
  README.Rmd
  README.md
  man/figures/README-volcano-1.png
  vignettes/data_analysis_dose_response_workflow.Rmd
  vignettes/data_analysis_single_dose_treatment_workflow.Rmd
  vignettes/input_preparation_workflow.Rmd
  vignettes/quality_control_workflow.Rmd
Labels: documentation

#126 undo text justification
  README.Rmd
  README.md
Labels: documentation

#128 Add new feature and fix bugs
  NAMESPACE
  R/assign_missingness.R
  R/calculate_protein_abundance.R
  R/diff_abundance.R
  R/find_peptide.R
  R/median_normalisation.R
  R/parallel_fit_drc_4p.R
  R/peptide_type.R
  R/plot_drc_4p.R
  R/plot_peptide_profiles.R
  R/plot_pval_distribution.R
  R/qc_charge_states.R
  R/qc_contaminants.R
  R/qc_cvs.R
  R/qc_data_completeness.R
  R/qc_ids.R
  R/qc_intensity_distribution.R
  R/qc_missed_cleavages.R
  R/qc_pca.R
  R/qc_peak_width.R
  R/qc_peptide_type.R
  R/qc_proteome_coverage.R
  R/qc_sample_correlation.R
  R/qc_sequence_coverage.R
  R/sequence_coverage.R
  R/volcano_protti.R
  README.Rmd
  README.md
  man/assign_missingness.Rd
  man/calculate_protein_abundance.Rd
  man/diff_abundance.Rd
  man/figures/README-volcano-1.png
  man/peptide_type.Rd
  man/plot_drc_4p.Rd
  man/plot_peptide_profiles.Rd
  man/plot_pval_distribution.Rd
  man/qc_charge_states.Rd
  man/qc_contaminants.Rd
  man/qc_cvs.Rd
  man/qc_data_completeness.Rd
  man/qc_ids.Rd
  man/qc_intensity_distribution.Rd
  man/qc_missed_cleavages.Rd
  man/qc_pca.Rd
  man/qc_peak_width.Rd
  man/qc_peptide_type.Rd
  man/qc_sample_correlation.Rd
  man/qc_sequence_coverage.Rd
  man/volcano_protti.Rd
  tests/testthat/test-auxiliary_functions.R
  tests/testthat/test-qc_functions.R
  tests/testthat/test-workflow.R
  vignettes/data_analysis_dose_response_workflow.Rmd
  vignettes/data_analysis_single_dose_treatment_workflow.Rmd
  vignettes/quality_control_workflow.Rmd
Labels: bug, documentation, enhancement, new feature

#129 qc vignette and data analysis vignette changes
  vignettes/data_analysis_single_dose_treatment_workflow.Rmd
  vignettes/quality_control_workflow.Rmd
Labels: documentation

#127 changes in input vignette
  vignettes/input_preparation_workflow.Rmd
Labels: documentation

#131 Remove proDA tests
  tests/testthat/test-workflow.R
Labels: bug

#132 Remove fetch_chebi tests
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
Labels: bug

#133 Fix urls note
  DESCRIPTION
  cran-comments.md
  vignettes/data_analysis_dose_response_workflow.Rmd
  vignettes/input_preparation_workflow.Rmd
Labels: bug

#134 Reduce test time and make tests conditional
  .github/workflows/R-CMD-check.yaml
  .github/workflows/test-coverage.yaml
  DESCRIPTION
  R/calculate_protein_abundance.R
  R/qc_pca.R
  R/qc_sample_correlation.R
  R/replace_identified_by_x.R
  cran-comments.md
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
  tests/testthat/test-qc_functions.R
  tests/testthat/test-workflow.R
  vignettes/data_analysis_dose_response_workflow.Rmd
  vignettes/data_analysis_single_dose_treatment_workflow.Rmd
  vignettes/quality_control_workflow.Rmd
Labels: issue

#135 Fix pkgdown vignettes
  .github/workflows/pkgdown.yaml
Labels: bug

#136 Set env variable in pgdown
  .github/workflows/pkgdown.yaml
Labels: bug

#137 Add LiP citation
  DESCRIPTION
  cran-comments.md
Labels: documentation

#138 Fix and improve examples
  R/calculate_imputation.R
  R/calculate_protein_abundance.R
  R/create_queue.R
  R/create_synthetic_data.R
  R/drc_4p.R
  R/extract_metal_binders.R
  R/fetch_chebi.R
  R/fetch_go.R
  R/fetch_kegg.R
  R/fetch_mobidb.R
  R/fetch_uniprot.R
  R/fetch_uniprot_proteome.R
  R/find_all_subs.R
  R/find_chebis.R
  R/find_peptide.R
  R/median_normalisation.R
  R/peptide_type.R
  R/qc_pca.R
  R/randomise_queue.R
  R/replace_identified_by_x.R
  R/scale_protti.R
  R/sequence_coverage.R
  R/split_metal_name.R
  R/try_query.R
  R/ttest_protti.R
  cran-comments.md
  man/calculate_imputation.Rd
  man/create_queue.Rd
  man/create_synthetic_data.Rd
  man/drc_4p.Rd
  man/extract_metal_binders.Rd
  man/fetch_chebi.Rd
  man/fetch_go.Rd
  man/fetch_kegg.Rd
  man/fetch_mobidb.Rd
  man/fetch_uniprot.Rd
  man/fetch_uniprot_proteome.Rd
  man/find_all_subs.Rd
  man/find_chebis.Rd
  man/find_peptide.Rd
  man/median_normalisation.Rd
  man/peptide_type.Rd
  man/randomise_queue.Rd
  man/replace_identified_by_x.Rd
  man/scale_protti.Rd
  man/sequence_coverage.Rd
  man/split_metal_name.Rd
  man/try_query.Rd
  man/ttest_protti.Rd
  tests/testthat/test-auxiliary_functions.R
Labels: enhancement

#139 update readme and vignettes
  README.Rmd
  README.md
  man/figures/README-volcano-1.png
  vignettes/input_preparation_workflow.Rmd
  vignettes/quality_control_workflow.Rmd
Labels: documentation
