Repository jpquast/protti, pull requests merged in 2022-03, with the labels that each got.

#165 Small correction
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/analyse_functional_network.R
  R/assign_peptide_type.R
  R/barcode_plot.R
  R/calculate_aa_scores.R
  R/calculate_diff_abundance.R
  R/calculate_go_enrichment.R
  R/calculate_kegg_enrichment.R
  R/calculate_protein_abundance.R
  R/calculate_sequence_coverage.R
  R/calculate_treatment_enrichment.R
  R/create_structure_contact_map.R
  R/drc_4p_plot.R
  R/fetch_alphafold_prediction.R
  R/fetch_chebi.R
  R/fetch_kegg.R
  R/fetch_metal_pdb.R
  R/fetch_mobidb.R
  R/fetch_pdb.R
  R/fetch_pdb_structure.R
  R/fetch_uniprot.R
  R/fetch_uniprot_proteome.R
  R/map_peptides_on_structure.R
  R/normalise.R
  R/peptide_profile_plot.R
  R/pval_distribution_plot.R
  R/qc_contaminants.R
  R/qc_peak_width.R
  R/try_query.R
  R/volcano_plot.R
  cran-comments.md
  man/analyse_functional_network.Rd
  man/barcode_plot.Rd
  man/calculate_aa_scores.Rd
  man/diff_abundance.Rd
  man/drc_4p_plot.Rd
  man/go_enrichment.Rd
  man/kegg_enrichment.Rd
  man/median_normalisation.Rd
  man/network_analysis.Rd
  man/peptide_type.Rd
  man/plot_drc_4p.Rd
  man/plot_peptide_profiles.Rd
  man/plot_pval_distribution.Rd
  man/pval_distribution_plot.Rd
  man/qc_contaminants.Rd
  man/qc_peak_width.Rd
  man/sequence_coverage.Rd
  man/treatment_enrichment.Rd
  man/volcano_protti.Rd
  tests/testthat/test-structure_functions.R
  vignettes/data_analysis_single_dose_treatment_workflow.Rmd
Labels: bug, issue

#166 Add fetch_eco and improve test coverage
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/fetch_eco.R
  man/fetch_eco.Rd
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
  tests/testthat/test-structure_functions.R
Labels: enhancement, new feature

#167 Improve test coverage
  R/fetch_alphafold_prediction.R
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
  tests/testthat/test-structure_functions.R
Labels: enhancement

#168 Add citation badge
  README.Rmd
  README.md
  man/figures/README-volcano-1.png
Labels: enhancement

#157 Add protein structure vignette
  DESCRIPTION
  NEWS.md
  R/map_peptides_on_structure.R
  README.Rmd
  README.md
  man/figures/README-volcano-1.png
  vignettes/figures/interaction_2hwg.png
  vignettes/figures/peptide_map_1zmr.png
  vignettes/figures/peptide_map_1zmr_score.png
  vignettes/figures/peptide_map_2hwg.png
  vignettes/figures/peptide_map_2hwg_score.png
  vignettes/protein_structure_workflow.Rmd
Labels: documentation

#169 Bug fixes
  NEWS.md
  R/pval_distribution_plot.R
  R/qc_proteome_coverage.R
  R/volcano_plot.R
  man/pval_distribution_plot.Rd
  man/qc_proteome_coverage.Rd
  man/volcano_plot.Rd
  vignettes/protein_structure_workflow.Rmd
Labels: bug, enhancement

#170 Correct formating
  vignettes/protein_structure_workflow.Rmd
Labels: documentation
