Repository jpquast/protti, pull requests merged in 2024-10, with the labels that each got.

#270 Developer
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/calculate_protein_abundance.R
  R/data.R
  R/fetch_eco.R
  R/fetch_mobidb.R
  R/try_query.R
  README.Rmd
  README.md
  cran-comments.md
  man/calculate_protein_abundance.Rd
  man/fetch_eco.Rd
  man/fetch_mobidb.Rd
  man/figures/README-volcano-1.png
  man/ptsi_pgk.Rd
  man/rapamycin_10uM.Rd
  man/rapamycin_dose_response.Rd
  man/try_query.Rd
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
  vignettes/data_analysis_dose_response_workflow.Rmd
  vignettes/data_analysis_single_dose_treatment_workflow.Rmd
  vignettes/input_preparation_workflow.Rmd
Labels: bug

#263 Improve assign peptide type 243
  DESCRIPTION
  NEWS.md
  R/assign_peptide_type.R
  R/qc_cvs.R
  man/assign_peptide_type.Rd
  tests/testthat/test-auxiliary_functions.R
  vignettes/data_analysis_single_dose_treatment_workflow.Rmd
Labels: enhancement

#275 Fix assign missingness issue
  NEWS.md
  R/assign_missingness.R
Labels: bug

#276 Calculate go enrichment improvement
  NEWS.md
  R/calculate_go_enrichment.R
  man/calculate_go_enrichment.Rd
Labels: bug, enhancement

#277 Fetch pdb improvement
  NEWS.md
  R/fetch_pdb.R
  R/find_peptide_in_structure.R
  man/find_peptide_in_structure.Rd
  tests/testthat/test-fetch_extract_and_enrichment_functions.R
  tests/testthat/test-structure_functions.R
Labels: bug, enhancement
